apiVersion: v1
kind: Service
metadata:
  name: nokiafilestoreapi
  labels:
    run: nokiafilestoreapi
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: nokia-file-store-pod
  type: NodePort
